# Generated by Django 4.2.4 on 2024-05-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customerregistrationmodel_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerregistrationmodel',
            old_name='passwors2',
            new_name='password2',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('MS', 'Milkshake'), ('CR', 'Curd'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('ML', 'Milk'), ('LS', 'Lassi'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
