# Generated by Django 4.2.4 on 2024-05-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_passwors2_customerregistrationmodel_password2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerRegistrationModel',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('CR', 'Curd'), ('MS', 'Milkshake'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('ML', 'Milk'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese')], max_length=2),
        ),
    ]
