# Generated by Django 4.2.4 on 2024-05-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('ML', 'Milk'), ('PN', 'Paneer'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
